services:
  # Web service для основного приложения
  - type: web
    name: bnal-bank
    env: node
    plan: starter
    buildCommand: ./build.sh
    startCommand: ./start.sh
    rootDir: render-app
    healthCheckPath: /api/render-status
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: WEBAPP_URL
        fromService:
          name: bnal-bank
          type: web
          property: url
    disk:
      name: data
      mountPath: /data
      sizeGB: 1